### ISSUE TITLE
Deployment information shouldn't be in the repository

### ISSUE THREAD

**Issue by cwant** [ualbertalib/DMPonline_v4#136]
* The file `.bundle/config` [1] tells bundler where to install it's bundle. The decision where to install the bundle should be made by those deploying the app, not the developers. The directory `.bundle` should be removed.
* The directory `vendor/ruby` [2] was installed by bundler and has many platform/OS-specific binaries. It should be removed from this repository because it affects the portability of this project.

For deployment, `bundle install --deployment` should be called to install the gems where ever needed. For example, see `projects/avalon/roles/avalon_app/templates/deploy.sh.j2` from the U of A `ansible-config` playbook.

[1] https://github.com/ualbertalib/DMPonline_v4/tree/deployment-portage/.bundle
[2] https://github.com/ualbertalib/DMPonline_v4/tree/deployment-portage/vendor/ruby/2.1.0

**Comment by weiweishi** [comment]
@nmacgreg let's have a quick meeting to revisit our DMP deployment procedure and remove these from the codebase.

**Comment by murny** [comment]
Not only should you remove them from the repo, but you should also erase all these binaries from the git history too. Which is an even harder task to do.

This project is now almost 400MB because of this which is crazy (for comparison HN is only 10mb and is a much bigger project and probably isnt a golden example as we have binaries in this repo too. Or jupiter is 300 kb).  Reason why you dont check in binaries in git!!!
