### ISSUE TITLE
i18n: Home page French translation

### ISSUE THREAD

**Issue by umarqasim** [ualbertalib/DMPonline_v4#58]
On dmptest server, the four steps listed on the home page are not being translated to french.

**Comment by weiweishi** [comment]
this is because UofM hasn't provided the French translation yet. They are
working on it right now. Thanks!

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by mhvezina** [comment]
Done.
