### ISSUE TITLE
DMP Assistant Admin Pages: Guidance group and list problems

### ISSUE THREAD

**Issue by jasonbrodeur** [ualbertalib/DMPonline_v4#92]
Good afternoon, 

It seems we (McMaster) are still experiencing some issues with our Admin functionality. Within the guidance tab of the admin area, we are unable to create a guidance group list for any specific template (our only template option to select is "All templates"), and when trying to "Add guidance", we get a white error page with red text "We're sorry, but something went wrong."

Thanks,
Jay

**Comment by weiweishi** [comment]
Okay Jay. I will look into this. There will be a new release of DMP this
week, and I hope to bundle the fix to this issue into this release.

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca

**Comment by weiweishi** [comment]
closed with Commit cd0a8f82c820

**Comment by weiweishi** [comment]
Hi Jay

The new release is deployed, and this should have fixed the issue you
experienced. Please let me know otherwise?

Weiwei

*Weiwei Shi*

Digital Initiative Applications Librarian
University of Alberta Libraries
2-10L Cameron Library
Edmonton, Alberta, Canada T6G 2J8
Phone:(780)492-7802
Fax: (780)248-1209
Email: weiwei.shi@ualberta.ca
